version: '3.8'

services:
  caddyshack-ui:
    build: .
    container_name: caddyshack-ui
    ports:
      - "${CADDYSHACK_PORT:-8080}:3000"
    environment:
      - TZ=${TIMEZONE:-UTC}
      - CADDYFILE_PATH=/caddy/Caddyfile
      - CADDY_ADMIN_ENDPOINT=${CADDY_ADMIN_ENDPOINT:-http://host.docker.internal:2019}
    volumes:
      - ${CADDYFILE_LOCATION:-./Caddyfile}:/caddy/Caddyfile
      - caddyfile_backups:/app/backups
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - caddyshack-network

volumes:
  caddyfile_backups:

networks:
  caddyshack-network:
    driver: bridge
