version: '3.8'

services:
  caddyshack-ui:
    image: ghcr.io/loryanstrant/caddyshack:latest
    # Uncomment the line below and comment the image line above to build locally
    # build: .
    container_name: caddyshack-ui
    ports:
      - "${CADDYSHACK_PORT:-8080}:3000"
    environment:
      - TZ=${TIMEZONE:-UTC}
      - CADDYFILE_PATH=/caddy/Caddyfile
      - CADDY_ADMIN_ENDPOINT=${CADDY_ADMIN_ENDPOINT:-http://host.docker.internal:2019}
    volumes:
      - ${CADDYFILE_LOCATION:-./Caddyfile}:/caddy/Caddyfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - caddyshack-network

networks:
  caddyshack-network:
    driver: bridge
